spring:
  devtools:
    restart:
      enabled: false
  datasource:
    username: postgres
    password: Jbt1234!
    url: jdbc:postgresql://localhost:5432/yw_drone
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    defer-datasource-initialization: false
    database: postgresql
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  sql:
    init:
      mode: never
  web:
    resources:
      static-locations:
        - file:///C:/extern/
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
    com.ejbt.drone.yeongwol: debug

app:
  dem-path: 'file:///C:/extern/cop30.tif'
